language: go
os: linux
sudo: required
services:
- docker
go:
- 1.11.x
go_import_path: github.com/kubedev/kubectl-config-merge
before_install:
- go get -u github.com/golang/dep/cmd/dep
script:
- make dep
- make