
[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.0"

[[constraint]]
  name = "k8s.io/cli-runtime"
  branch = "release-1.12"

[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "release-1.12"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.12"

[prune]
  go-tests = true
  unused-packages = true
